//! REST and SSE transport for AI agent endpoints.

use std::future::Future;

use anyhow::{Context, Result};
use async_trait::async_trait;
use serde_json::Value;

use super::events::{parse_data_line, AgentEvent, SseLineBuffer};
use super::render::strip_control_chars;
use crate::cli::api::http_get;

/// Take a token from the process-wide rate limiter before issuing an agent
/// HTTP call, so agent traffic shares one 10 req/s budget with every other
/// command (quotes, trades, …) instead of running an unmetered lane.
///
/// `acquire()` rather than `RateLimiter::execute()`: `execute` layers its own
/// retry/backoff on any error whose text contains "429", which would nest
/// inside [`with_rate_limit_retry`] and multiply the wait. The retry policy
/// for agent calls lives in one place; the limiter only meters.
async fn acquire_rate_limit_token(request_name: &str) {
    tracing::debug!("Rate-limited agent request: {request_name}");
    crate::openapi::global_rate_limiter().acquire().await;
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct WorkspaceInfo {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub created_at: i64,
    #[serde(default)]
    pub updated_at: i64,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AgentInfo {
    pub uid: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub mode: String,
    #[serde(default)]
    pub is_published: bool,
    /// Filled by the caller during traversal, not present in the API payload.
    #[serde(default)]
    pub workspace_id: String,
    #[serde(default)]
    pub workspace_name: String,
}

pub struct AgentPage {
    pub agents: Vec<AgentInfo>,
    pub total: u32,
}

/// Agent discovery API. Implementations wrap the real REST endpoints; tests
/// use a mock generated by `mockall`.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait AgentApi: Send + Sync {
    async fn list_workspaces(&self) -> Result<Vec<WorkspaceInfo>>;
    async fn list_agents(
        &self,
        workspace_id: String,
        page: u32,
        limit: u32,
        name: Option<String>,
    ) -> Result<AgentPage>;
}

pub struct LbAgentApi {
    pub verbose: bool,
}

#[async_trait]
impl AgentApi for LbAgentApi {
    async fn list_workspaces(&self) -> Result<Vec<WorkspaceInfo>> {
        let resp = with_rate_limit_retry(|| async {
            acquire_rate_limit_token("agent_list_workspaces").await;
            http_get("/v1/ai/workspaces", &[], self.verbose).await
        })
        .await?;
        let workspaces = resp
            .get("workspaces")
            .cloned()
            .unwrap_or(Value::Array(Vec::new()));
        serde_json::from_value(workspaces).context("Unexpected workspaces payload")
    }

    async fn list_agents(
        &self,
        workspace_id: String,
        page: u32,
        limit: u32,
        name: Option<String>,
    ) -> Result<AgentPage> {
        let path = format!("/v1/ai/workspaces/{workspace_id}/agents");
        let page_s = page.to_string();
        let limit_s = limit.to_string();
        let mut params: Vec<(&str, &str)> = vec![("page", &page_s), ("limit", &limit_s)];
        if let Some(n) = name.as_deref() {
            params.push(("name", n));
        }
        let resp = with_rate_limit_retry(|| async {
            acquire_rate_limit_token("agent_list_agents").await;
            http_get(&path, &params, self.verbose).await
        })
        .await?;
        let agents = resp
            .get("agents")
            .cloned()
            .unwrap_or(Value::Array(Vec::new()));
        let total = resp.get("total").and_then(Value::as_u64).unwrap_or(0) as u32;
        Ok(AgentPage {
            agents: serde_json::from_value(agents).context("Unexpected agents payload")?,
            total,
        })
    }
}

/// True when the error is the `OpenAPI` 429002 rate-limit rejection.
pub fn is_rate_limited(err: &anyhow::Error) -> bool {
    let s = err.to_string();
    s.contains("429002") || s.contains("slow down request frequency")
}

#[cfg(test)]
const BACKOFF_SECS: [f64; 3] = [0.01, 0.02, 0.04];
#[cfg(not(test))]
const BACKOFF_SECS: [f64; 3] = [1.0, 2.0, 4.0];

/// Run `op`, retrying up to 3 times with exponential backoff when the API
/// rejects the call with a 429002 rate limit.
pub async fn with_rate_limit_retry<T, F, Fut>(mut op: F) -> Result<T>
where
    F: FnMut() -> Fut,
    Fut: Future<Output = Result<T>>,
{
    for backoff in BACKOFF_SECS {
        match op().await {
            Ok(v) => return Ok(v),
            Err(e) if is_rate_limited(&e) => {
                tokio::time::sleep(std::time::Duration::from_secs_f64(backoff)).await;
            }
            Err(e) => return Err(e),
        }
    }
    // Final attempt after backoff is exhausted: propagate whatever error it
    // actually produces. A stale 429 from an earlier attempt must not mask
    // a different, more informative failure on this last try (e.g. the
    // server may have moved on to rejecting the request outright).
    op().await
}

/// Reject AI conversations when the process authenticated with API-key env
/// vars. The SSE transport sends a plain OAuth bearer token and implements no
/// request signing, so in API-key mode it would either fail with an opaque
/// 401 or (worse) act as a different principal than the `agent list` calls
/// that go through the SDK client. Fail fast with something actionable.
fn ensure_oauth_auth(using_api_key: bool) -> Result<()> {
    if using_api_key {
        anyhow::bail!(
            "agent chat requires OAuth login (API-key auth is not supported for AI \
             conversations); run `longbridge auth login`"
        );
    }
    Ok(())
}

/// Turn a non-SSE (error) conversation response into an `anyhow::Error`.
///
/// Error responses come back as a plain JSON envelope, e.g. 429002. The
/// rendered message intentionally contains the numeric code so
/// [`is_rate_limited`] can classify it and the caller can retry.
fn conversation_envelope_error(status: reqwest::StatusCode, text: &str) -> anyhow::Error {
    // `message` (and the raw-body fallback) is server text printed straight to
    // the terminal by the error handler, so it is sanitized here — an error
    // path is no less of a terminal-escape sink than the success path.
    let (code, message) = serde_json::from_str::<Value>(text).map_or_else(
        |_| {
            (
                0,
                strip_control_chars(&text.chars().take(200).collect::<String>()),
            )
        },
        |v| {
            (
                v.get("code").and_then(Value::as_i64).unwrap_or_default(),
                strip_control_chars(v.get("message").and_then(Value::as_str).unwrap_or_default()),
            )
        },
    );
    let hint = if code == 429_002 {
        " -- rate limited: serialize requests and wait a few seconds before retrying"
    } else if status == reqwest::StatusCode::BAD_REQUEST {
        " -- run `longbridge agent list` to confirm the agent uid exists and is published"
    } else {
        ""
    };
    anyhow::anyhow!("Conversation request failed (HTTP {status}, code={code}): {message}{hint}")
}

/// POST the conversation request and return the response only once the server
/// has accepted it and is actually streaming SSE. Everything here happens
/// *before* a single SSE frame is consumed, which is what makes the 429002
/// path safe to retry: the request was rejected outright, so replaying it
/// cannot duplicate a partially delivered agent run.
async fn post_conversation(
    client: &reqwest::Client,
    url: &str,
    token: &str,
    body: &Value,
) -> Result<reqwest::Response> {
    let resp = client
        .post(url)
        .header("authorization", format!("Bearer {token}"))
        .header("accept", "text/event-stream")
        .json(body)
        .send()
        .await
        .context("Failed to reach the AI conversation endpoint")?;

    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or_default()
        .to_string();
    if !resp.status().is_success() || !content_type.contains("text/event-stream") {
        let status = resp.status();
        let text = resp.text().await.unwrap_or_default();
        return Err(conversation_envelope_error(status, &text));
    }
    Ok(resp)
}

/// POST a conversation request and stream SSE events to `on_event`.
///
/// Uses reqwest directly: the SDK `HttpClient` cannot stream responses.
/// Auth is a plain Bearer token, valid on both access points.
pub async fn stream_conversation(
    path: &str,
    body: Value,
    verbose: bool,
    on_event: &mut dyn FnMut(AgentEvent),
) -> Result<()> {
    ensure_oauth_auth(crate::openapi::using_api_key())?;
    crate::auth::refresh_if_expired().await?;
    let token = crate::auth::access_token()?;
    let url = format!("{}{}", crate::openapi::effective_http_url(), path);
    if verbose {
        eprintln!("* POST {url} (SSE)");
    }
    // `read_timeout` in reqwest 0.12 bounds the gap between chunks, not the
    // whole response body; the server sends periodic `ping` SSE events
    // during long-running agent turns, so a live stream keeps resetting it
    // and 60s only fires on a genuinely stalled connection.
    let client = reqwest::Client::builder()
        .connect_timeout(std::time::Duration::from_secs(10))
        .read_timeout(std::time::Duration::from_secs(60))
        .build()
        .context("Failed to build HTTP client")?;

    // Retry only covers the pre-stream handshake, and only for the 429002
    // rejection: transport errors are ambiguous (the server may already be
    // running the turn) and are never replayed, and once the first SSE frame
    // is read below no retry happens at all.
    let mut resp = with_rate_limit_retry(|| async {
        acquire_rate_limit_token("agent_conversation").await;
        post_conversation(&client, &url, &token, &body).await
    })
    .await?;

    let mut buf = SseLineBuffer::default();
    while let Some(chunk) = resp.chunk().await.context("SSE stream dropped")? {
        for payload in buf.push(&chunk) {
            if let Some(ev) = parse_data_line(&payload) {
                on_event(ev);
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use serial_test::serial;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::Arc;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    /// Serve canned HTTP responses on an ephemeral port, one per accepted
    /// connection, counting requests. A real socket keeps the test honest
    /// about reqwest's behaviour without touching the live API.
    async fn spawn_scripted_server(responses: Vec<String>) -> (u16, Arc<AtomicUsize>) {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let port = listener.local_addr().unwrap().port();
        let hits = Arc::new(AtomicUsize::new(0));
        let counter = Arc::clone(&hits);
        tokio::spawn(async move {
            loop {
                let Ok((mut socket, _)) = listener.accept().await else {
                    return;
                };
                let n = counter.fetch_add(1, Ordering::SeqCst);
                let mut buf = [0u8; 4096];
                let mut data = Vec::new();
                while !data.windows(4).any(|w| w == b"\r\n\r\n") {
                    match socket.read(&mut buf).await {
                        Ok(0) | Err(_) => break,
                        Ok(k) => data.extend_from_slice(&buf[..k]),
                    }
                }
                let body = responses
                    .get(n)
                    .cloned()
                    .unwrap_or_else(|| responses.last().cloned().unwrap_or_default());
                let _ = socket.write_all(body.as_bytes()).await;
                let _ = socket.flush().await;
                let _ = socket.shutdown().await;
            }
        });
        (port, hits)
    }

    fn http_response(status_line: &str, content_type: &str, body: &str) -> String {
        format!(
            "HTTP/1.1 {status_line}\r\nContent-Type: {content_type}\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
            body.len()
        )
    }

    #[test]
    fn api_key_mode_is_rejected_with_actionable_message() {
        let err = ensure_oauth_auth(true).unwrap_err().to_string();
        assert!(err.contains("OAuth"), "unexpected message: {err}");
        assert!(
            err.contains("longbridge auth login"),
            "message must be actionable: {err}"
        );
        ensure_oauth_auth(false).expect("OAuth mode must be allowed");
    }

    #[test]
    fn envelope_error_for_429002_is_classified_as_rate_limited() {
        let err = conversation_envelope_error(
            reqwest::StatusCode::TOO_MANY_REQUESTS,
            r#"{"code":429002,"message":"api request is limited"}"#,
        );
        assert!(is_rate_limited(&err), "429002 envelope must retry: {err}");
    }

    #[test]
    fn envelope_error_for_bad_request_is_not_rate_limited() {
        let err = conversation_envelope_error(
            reqwest::StatusCode::BAD_REQUEST,
            r#"{"code":400,"message":"agent not published"}"#,
        );
        assert!(!is_rate_limited(&err));
        assert!(err.to_string().contains("agent list"));
    }

    #[test]
    fn envelope_error_strips_control_chars_from_server_message() {
        let err = conversation_envelope_error(
            reqwest::StatusCode::BAD_REQUEST,
            "{\"code\":400,\"message\":\"bad \x1b]0;pwn\x07agent\"}",
        )
        .to_string();
        assert!(!err.contains('\x1b'), "ESC survived: {err:?}");
        assert!(!err.contains('\x07'), "BEL survived: {err:?}");
        assert!(err.contains("agent"));

        // Same for the non-JSON raw-body fallback.
        let err = conversation_envelope_error(
            reqwest::StatusCode::BAD_GATEWAY,
            "<html>\x1b[31mgateway\x1b[0m</html>",
        )
        .to_string();
        assert!(!err.contains('\x1b'), "ESC survived: {err:?}");
    }

    /// Agent traffic must consume the same 10 req/s budget as every other
    /// command, not run in an unmetered lane beside it.
    #[tokio::test]
    #[serial]
    async fn conversation_post_consumes_shared_rate_limiter_tokens() {
        let ok = http_response("200 OK", "text/event-stream", "data:{}\n\n");
        let (port, hits) = spawn_scripted_server(vec![ok]).await;
        let client = reqwest::Client::new();
        let url = format!("http://127.0.0.1:{port}/v1/ai/agents/x/conversations");
        let body = serde_json::json!({"query": "hi"});

        let before = crate::openapi::global_rate_limiter().available_tokens();
        with_rate_limit_retry(|| async {
            acquire_rate_limit_token("agent_conversation").await;
            post_conversation(&client, &url, "tok", &body).await
        })
        .await
        .unwrap();
        let after = crate::openapi::global_rate_limiter().available_tokens();

        assert_eq!(hits.load(Ordering::SeqCst), 1);
        assert_eq!(
            before - after,
            1,
            "one request must take exactly one shared token"
        );
    }

    #[tokio::test]
    #[serial]
    async fn conversation_post_retries_pre_stream_rate_limit() {
        let limited = http_response(
            "429 Too Many Requests",
            "application/json",
            r#"{"code":429002,"message":"api request is limited"}"#,
        );
        let ok = http_response(
            "200 OK",
            "text/event-stream",
            "data:{\"event\":\"chat_started\",\"data\":{}}\n\n",
        );
        let (port, hits) = spawn_scripted_server(vec![limited.clone(), limited, ok]).await;
        let client = reqwest::Client::new();
        let url = format!("http://127.0.0.1:{port}/v1/ai/agents/x/conversations");
        let body = serde_json::json!({"query": "hi"});

        let before = crate::openapi::global_rate_limiter().available_tokens();
        let resp = with_rate_limit_retry(|| async {
            acquire_rate_limit_token("agent_conversation").await;
            post_conversation(&client, &url, "tok", &body).await
        })
        .await
        .expect("retry must recover from the pre-stream 429002");
        let after = crate::openapi::global_rate_limiter().available_tokens();

        assert_eq!(hits.load(Ordering::SeqCst), 3, "expected two retries");
        assert_eq!(before - after, 3, "every attempt must take a token");
        let text = resp.text().await.unwrap();
        assert!(text.contains("chat_started"));
    }

    #[tokio::test]
    async fn conversation_post_does_not_retry_other_errors() {
        let bad = http_response(
            "400 Bad Request",
            "application/json",
            r#"{"code":400,"message":"agent not published"}"#,
        );
        let (port, hits) = spawn_scripted_server(vec![bad]).await;
        let client = reqwest::Client::new();
        let url = format!("http://127.0.0.1:{port}/v1/ai/agents/x/conversations");
        let body = serde_json::json!({"query": "hi"});

        let err = with_rate_limit_retry(|| post_conversation(&client, &url, "tok", &body))
            .await
            .unwrap_err();

        assert_eq!(hits.load(Ordering::SeqCst), 1, "400 must not be retried");
        assert!(err.to_string().contains("agent not published"));
    }

    #[test]
    fn rate_limited_detects_429002() {
        assert!(is_rate_limited(&anyhow::anyhow!(
            "api error: code=429002 api request is limited"
        )));
        assert!(is_rate_limited(&anyhow::anyhow!(
            "please slow down request frequency"
        )));
        assert!(!is_rate_limited(&anyhow::anyhow!("404 not found")));
    }

    #[test]
    fn agent_info_deserializes_from_api_shape() {
        let json = serde_json::json!({
            "uid": "chatbot", "name": "LongbridgeAI", "mode": "chat",
            "is_published": true, "created_at": 1, "updated_at": 2
        });
        let a: AgentInfo = serde_json::from_value(json).unwrap();
        assert_eq!(a.uid, "chatbot");
        assert!(a.is_published);
        assert_eq!(a.workspace_id, ""); // filled later by traversal
        assert_eq!(a.description, ""); // optional in API
    }

    #[test]
    fn workspace_info_deserializes() {
        let json =
            serde_json::json!({"id": "33", "name": "Longbridge", "created_at": 0, "updated_at": 0});
        let w: WorkspaceInfo = serde_json::from_value(json).unwrap();
        assert_eq!(w.id, "33");
    }

    #[tokio::test]
    async fn retry_helper_retries_on_rate_limit_then_succeeds() {
        let mut calls = 0;
        let result = with_rate_limit_retry(|| {
            calls += 1;
            let attempt = calls;
            async move {
                if attempt < 2 {
                    Err(anyhow::anyhow!("code=429002 api request is limited"))
                } else {
                    Ok(42)
                }
            }
        })
        .await
        .unwrap();
        assert_eq!(result, 42);
        assert_eq!(calls, 2);
    }

    #[tokio::test]
    async fn retry_helper_passes_through_other_errors() {
        let result: anyhow::Result<i32> =
            with_rate_limit_retry(|| async { Err(anyhow::anyhow!("boom")) }).await;
        assert_eq!(result.unwrap_err().to_string(), "boom");
    }

    #[tokio::test]
    async fn retry_helper_final_attempt_error_is_not_masked_by_stale_429() {
        // Every attempt inside the backoff loop is rate-limited; the final
        // (post-backoff) attempt fails with a *different* error. The
        // returned error must be that final failure, not a stale 429 from
        // an earlier attempt.
        let mut calls = 0;
        let result: anyhow::Result<i32> = with_rate_limit_retry(|| {
            calls += 1;
            let attempt = calls;
            async move {
                if attempt <= BACKOFF_SECS.len() {
                    Err(anyhow::anyhow!("code=429002 api request is limited"))
                } else {
                    Err(anyhow::anyhow!("boom: real failure on last attempt"))
                }
            }
        })
        .await;
        assert_eq!(calls, BACKOFF_SECS.len() + 1);
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("boom: real failure on last attempt"),
            "expected the final attempt's real error, got: {err}"
        );
        assert!(!err.contains("429002"), "stale 429 leaked through: {err}");
    }
}
