//! REST and SSE transport for AI agent endpoints, backed by the SDK's
//! [`AgentContext`](longbridge::agent::AgentContext).

use std::pin::Pin;

use anyhow::{Context, Result};
use async_trait::async_trait;
use futures::{Stream, StreamExt};
use longbridge::agent::{ConversationStatus, ConversationStreamEvent, GetAgentsOptions};
use serde_json::json;

use super::events::AgentEvent;

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct WorkspaceInfo {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub created_at: i64,
    #[serde(default)]
    pub updated_at: i64,
}

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AgentInfo {
    pub uid: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub mode: String,
    #[serde(default)]
    pub is_published: bool,
    /// Filled by the caller during traversal, not present in the API payload.
    #[serde(default)]
    pub workspace_id: String,
    #[serde(default)]
    pub workspace_name: String,
}

pub struct AgentPage {
    pub agents: Vec<AgentInfo>,
    pub total: u32,
}

/// Agent discovery API. Implementations wrap the real endpoints; tests use a
/// mock generated by `mockall`.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait AgentApi: Send + Sync {
    async fn list_workspaces(&self) -> Result<Vec<WorkspaceInfo>>;
    async fn list_agents(
        &self,
        workspace_id: String,
        page: u32,
        limit: u32,
        name: Option<String>,
    ) -> Result<AgentPage>;
}

pub struct LbAgentApi {
    pub verbose: bool,
}

#[async_trait]
impl AgentApi for LbAgentApi {
    async fn list_workspaces(&self) -> Result<Vec<WorkspaceInfo>> {
        if self.verbose {
            eprintln!("* GET /v1/ai/workspaces");
        }
        // The shared limiter meters (10 req/s) and retries the 429002
        // rate-limit rejection with backoff. The op returns the raw SDK error
        // so the limiter's "429" detection can see the code; the user-facing
        // context is attached only after retries are exhausted.
        let resp = crate::openapi::global_rate_limiter()
            .execute("agent_list_workspaces", || {
                Box::pin(async { crate::openapi::agent().workspaces().await })
            })
            .await
            .context("Failed to list AI workspaces")?;
        Ok(resp
            .workspaces
            .into_iter()
            .map(|w| WorkspaceInfo {
                id: w.id,
                name: w.name,
                created_at: w.created_at,
                updated_at: w.updated_at,
            })
            .collect())
    }

    async fn list_agents(
        &self,
        workspace_id: String,
        page: u32,
        limit: u32,
        name: Option<String>,
    ) -> Result<AgentPage> {
        if self.verbose {
            eprintln!("* GET /v1/ai/workspaces/{workspace_id}/agents");
        }
        let mut opts = GetAgentsOptions::new()
            .page(i32::try_from(page).unwrap_or(i32::MAX))
            .limit(i32::try_from(limit).unwrap_or(i32::MAX));
        if let Some(n) = name {
            opts = opts.name(n);
        }
        let resp = crate::openapi::global_rate_limiter()
            .execute("agent_list_agents", || {
                let ws = workspace_id.clone();
                let opts = opts.clone();
                Box::pin(async move { crate::openapi::agent().agents(ws, Some(opts)).await })
            })
            .await
            .context("Failed to list AI agents")?;
        Ok(AgentPage {
            agents: resp
                .agents
                .into_iter()
                .map(|a| AgentInfo {
                    uid: a.uid,
                    name: a.name,
                    description: a.description,
                    mode: a.mode,
                    is_published: a.is_published,
                    // Filled by the caller during traversal.
                    workspace_id: String::new(),
                    workspace_name: String::new(),
                })
                .collect(),
            total: u32::try_from(resp.total).unwrap_or(0),
        })
    }
}

/// Reject AI conversations when the process authenticated with API-key env
/// vars. The AI conversation endpoints are only known to accept an OAuth
/// principal; failing fast with an actionable message beats an opaque 401
/// mid-stream. (Can be lifted once API-key auth is confirmed to work against
/// the AI endpoints, now that requests go through the SDK's signing client.)
fn ensure_oauth_auth(using_api_key: bool) -> Result<()> {
    if using_api_key {
        anyhow::bail!(
            "agent chat requires OAuth login (API-key auth is not supported for AI \
             conversations); run `longbridge auth login`"
        );
    }
    Ok(())
}

/// A conversation to stream: either a fresh round or the resumption of an
/// interrupted one. Mirrors the two SDK entry points
/// ([`AgentContext::conversation_streamed`](longbridge::agent::AgentContext::conversation_streamed)
/// and
/// [`continue_conversation_streamed`](longbridge::agent::AgentContext::continue_conversation_streamed)).
#[derive(Clone)]
pub enum ConversationRequest {
    New {
        agent_uid: String,
        query: String,
        chat_uid: Option<String>,
        parent_message_id: Option<String>,
    },
    Continue {
        agent_uid: String,
        chat_uid: String,
        message_id: String,
        answers: longbridge::agent::AnswersByToolCall,
    },
}

/// The final run status, as the lowercase wire string the outcome layer keys
/// on (`classify_outcome` in `chat.rs`).
fn status_str(status: ConversationStatus) -> String {
    match status {
        ConversationStatus::Succeeded => "succeeded",
        ConversationStatus::Interrupted => "interrupted",
        ConversationStatus::Failed => "failed",
        ConversationStatus::Stopped => "stopped",
    }
    .to_string()
}

/// Translate one SDK stream event into the CLI's [`AgentEvent`]. Returns
/// `None` for progress-only events the CLI does not surface (heartbeats,
/// subagent/tool-delegation timelines, plan updates, …); the aggregator
/// ignored these before, so dropping them here is behaviour-preserving.
fn map_event(ev: ConversationStreamEvent) -> Option<AgentEvent> {
    Some(match ev {
        ConversationStreamEvent::ChatStarted(p) => AgentEvent::ChatStarted {
            chat_uid: p.chat_uid,
            message_id: p.message_id,
        },
        ConversationStreamEvent::Message(p) => {
            // Only the final answer body is surfaced; `think`/`process`
            // progress messages are dropped like the other progress events.
            if p.message_type == "answer" {
                AgentEvent::AnswerDelta { text: p.text }
            } else {
                return None;
            }
        }
        ConversationStreamEvent::ThinkingStarted(_) => AgentEvent::ThinkingStarted,
        ConversationStreamEvent::ThinkingFinished(_) => AgentEvent::ThinkingFinished,
        ConversationStreamEvent::NodeToolUseStarted(p) => AgentEvent::ToolUseStarted {
            tool_name: p.tool_name,
        },
        ConversationStreamEvent::NodeToolUseFinished(p) => AgentEvent::ToolUseFinished {
            tool_name: p.tool_name,
            status: p.status,
        },
        ConversationStreamEvent::WorkflowFinished(resp) => AgentEvent::WorkflowFinished {
            status: status_str(resp.status),
            // Rebuild the `outputs` object the aggregator reads (`references`
            // and `further_questions`); the SDK already parsed them off the
            // raw event.
            outputs: json!({
                "references": resp.references,
                "further_questions": resp.further_questions,
            }),
            elapsed_time: Some(resp.elapsed_time),
            error_message: resp.error.map(|e| e.message).unwrap_or_default(),
        },
        ConversationStreamEvent::HumanInteractionRequired(resp) => {
            AgentEvent::HumanInteractionRequired {
                interrupt: serde_json::to_value(&resp.interrupt).unwrap_or(serde_json::Value::Null),
            }
        }
        ConversationStreamEvent::ChatFinished(p) => AgentEvent::ChatFinished {
            error_message: p.error_message,
        },
        ConversationStreamEvent::Other { event, .. } => AgentEvent::Unknown { event },
        // Progress-only events the CLI does not display.
        ConversationStreamEvent::Ping
        | ConversationStreamEvent::WorkflowStarted(_)
        | ConversationStreamEvent::SubagentStarted(_)
        | ConversationStreamEvent::SubagentProgress(_)
        | ConversationStreamEvent::SubagentFinished(_)
        | ConversationStreamEvent::AgentToolStarted(_)
        | ConversationStreamEvent::AgentToolProgress(_)
        | ConversationStreamEvent::AgentToolFinished(_)
        | ConversationStreamEvent::QueryMasked(_)
        | ConversationStreamEvent::PlanChanged(_)
        | ConversationStreamEvent::ContextCompressStarted(_)
        | ConversationStreamEvent::ContextCompressFinished(_)
        | ConversationStreamEvent::ChatTitleUpdated(_) => return None,
    })
}

type EventStream = Pin<Box<dyn Stream<Item = longbridge::Result<ConversationStreamEvent>> + Send>>;

/// Stream a conversation through the SDK's `AgentContext`, dispatching each
/// surfaced event to `on_event`.
///
/// The shared rate limiter meters and retries the pre-stream 429002 handshake
/// rejection: the op returns the raw SDK error (whose Display carries the
/// code) so the limiter can classify it, and only the handshake is retried —
/// once draining starts below, a mid-stream failure is propagated as-is.
pub async fn stream_conversation(
    req: ConversationRequest,
    verbose: bool,
    on_event: &mut dyn FnMut(AgentEvent),
) -> Result<()> {
    ensure_oauth_auth(crate::openapi::using_api_key())?;
    let ctx = crate::openapi::agent();
    if verbose {
        eprintln!("* POST agent conversation (SSE)");
    }
    let mut stream = crate::openapi::global_rate_limiter()
        .execute("agent_conversation", || {
            let req = req.clone();
            Box::pin(async move {
                let stream: EventStream = match req {
                    ConversationRequest::New {
                        agent_uid,
                        query,
                        chat_uid,
                        parent_message_id,
                    } => Box::pin(
                        ctx.conversation_streamed(agent_uid, query, chat_uid, parent_message_id)
                            .await?,
                    ),
                    ConversationRequest::Continue {
                        agent_uid,
                        chat_uid,
                        message_id,
                        answers,
                    } => Box::pin(
                        ctx.continue_conversation_streamed(
                            agent_uid, chat_uid, message_id, answers,
                        )
                        .await?,
                    ),
                };
                Ok::<_, longbridge::Error>(stream)
            })
        })
        .await
        .context("Failed to run the AI conversation")?;

    while let Some(item) = stream.next().await {
        let ev = item.context("SSE stream error")?;
        if let Some(mapped) = map_event(ev) {
            on_event(mapped);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn api_key_mode_is_rejected_with_actionable_message() {
        let err = ensure_oauth_auth(true).unwrap_err().to_string();
        assert!(err.contains("OAuth"), "unexpected message: {err}");
        assert!(
            err.contains("longbridge auth login"),
            "message must be actionable: {err}"
        );
        ensure_oauth_auth(false).expect("OAuth mode must be allowed");
    }

    #[test]
    fn status_str_maps_every_variant() {
        assert_eq!(status_str(ConversationStatus::Succeeded), "succeeded");
        assert_eq!(status_str(ConversationStatus::Interrupted), "interrupted");
        assert_eq!(status_str(ConversationStatus::Failed), "failed");
        assert_eq!(status_str(ConversationStatus::Stopped), "stopped");
    }

    #[test]
    fn workflow_finished_maps_status_and_outputs() {
        use longbridge::agent::{ConversationResponse, Reference};
        let resp = ConversationResponse {
            chat_uid: "c1".into(),
            message_id: "42".into(),
            status: ConversationStatus::Succeeded,
            answer: "hi".into(),
            references: Some(vec![Reference {
                index: 1,
                title: "t".into(),
                url: "u".into(),
            }]),
            further_questions: Some(vec!["What next?".into()]),
            elapsed_time: 1.5,
            interrupt: None,
            error: None,
        };
        let Some(AgentEvent::WorkflowFinished {
            status,
            outputs,
            elapsed_time,
            error_message,
        }) = map_event(ConversationStreamEvent::WorkflowFinished(resp))
        else {
            panic!("expected WorkflowFinished");
        };
        assert_eq!(status, "succeeded");
        assert_eq!(elapsed_time, Some(1.5));
        assert!(error_message.is_empty());
        assert_eq!(outputs["references"][0]["index"], 1);
        assert_eq!(outputs["further_questions"][0], "What next?");
    }

    #[test]
    fn human_interaction_maps_to_interrupt_value() {
        use longbridge::agent::{ConversationResponse, Interrupt, Question, QuestionOption};
        let resp = ConversationResponse {
            chat_uid: "c1".into(),
            message_id: "42".into(),
            status: ConversationStatus::Interrupted,
            answer: String::new(),
            references: None,
            further_questions: None,
            elapsed_time: 0.0,
            interrupt: Some(Interrupt {
                node_id: "n".into(),
                tool_call_id: "call_a".into(),
                questions: vec![Question {
                    question: "Which period?".into(),
                    options: vec![QuestionOption {
                        description: "1w".into(),
                    }],
                    multi_select: false,
                }],
                message_id: 42,
                chat_id: 1,
            }),
            error: None,
        };
        let Some(AgentEvent::HumanInteractionRequired { interrupt }) =
            map_event(ConversationStreamEvent::HumanInteractionRequired(resp))
        else {
            panic!("expected HumanInteractionRequired");
        };
        assert_eq!(interrupt["tool_call_id"], "call_a");
        assert_eq!(interrupt["questions"][0]["question"], "Which period?");
        assert_eq!(interrupt["questions"][0]["options"][0]["description"], "1w");
    }

    #[test]
    fn progress_only_events_are_dropped() {
        assert!(map_event(ConversationStreamEvent::Ping).is_none());
    }

    #[test]
    fn message_type_routes_answer_vs_process() {
        use longbridge::agent::MessagePayload;
        let answer = MessagePayload {
            text: "a".into(),
            message_type: "answer".into(),
            ..Default::default()
        };
        assert!(matches!(
            map_event(ConversationStreamEvent::Message(answer)),
            Some(AgentEvent::AnswerDelta { .. })
        ));
        let think = MessagePayload {
            text: "t".into(),
            message_type: "think".into(),
            ..Default::default()
        };
        // Non-answer progress messages are dropped, not surfaced.
        assert!(map_event(ConversationStreamEvent::Message(think)).is_none());
    }

    #[test]
    fn agent_info_deserializes_from_api_shape() {
        let json = serde_json::json!({
            "uid": "chatbot", "name": "LongbridgeAI", "mode": "chat",
            "is_published": true, "created_at": 1, "updated_at": 2
        });
        let a: AgentInfo = serde_json::from_value(json).unwrap();
        assert_eq!(a.uid, "chatbot");
        assert!(a.is_published);
        assert_eq!(a.workspace_id, ""); // filled later by traversal
        assert_eq!(a.description, ""); // optional in API
    }

    #[test]
    fn workspace_info_deserializes() {
        let json =
            serde_json::json!({"id": "33", "name": "Longbridge", "created_at": 0, "updated_at": 0});
        let w: WorkspaceInfo = serde_json::from_value(json).unwrap();
        assert_eq!(w.id, "33");
    }
}
